### ISSUE TITLE
Sensors not available after configuration

### ISSUE THREAD

**Issue by harryweiss** [tofuSCHNITZEL/home-assistant-wienerlinien#1]
**Version of the custom_component**
1.2.0

**Describe the bug**
After configuration the parameters as described I get an error. Sensors for the stations (stops) are not available.

**log**
2022-06-10 01:08:23 ERROR (MainThread) [homeassistant.components.hassio.handler] /store return code 500
2022-06-10 01:08:23 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /store

**Comment by tofuSCHNITZEL** [comment]
Hi,
sorry for the late reply. do you still have this issue? 
What is your HA version?

**Comment by tofuSCHNITZEL** [comment]
Not sure this is a problem with this integration or symptom of another issue with your installation... do you have more details/logs entries?
