### ISSUE TITLE
Sensors get deleted after a while

### ISSUE THREAD

**Issue by dexonter** [tofuSCHNITZEL/home-assistant-wienerlinien#3]
**Version of the custom_component**
1.2.0

**Describe the bug**
The sensors work for the 4 stops that I am tracking but stop working about 40 minutes later and they just dissapear

Not sure what logs to post or where to find them, they just simply disappear...

**Comment by tofuSCHNITZEL** [comment]
you can check the logs under Settings->System->logs

**Comment by dexonter** [comment]
Problem solved!

For anyone having issues with this... I always restarted HA in the middle of the night when there is no info and apparently there are no placeholders until some data is received...

So all you have to do is wait....
Or restart during the day..

**Comment by tofuSCHNITZEL** [comment]
this could also be fixed with [v1.2.1](https://github.com/tofuSCHNITZEL/home-assistant-wienerlinien/releases/tag/1.2.1) since it does not crash the whole extension if no data is available.
